// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udwcrxcohmibgefdpxsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkd2NyeGNvaG1pYmdlZmRweHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDE5NTEsImV4cCI6MjA3NDIxNzk1MX0.p94z8iwHYyiMU6KJeo7z4shn8hozWb_P8g2pHk6SQ7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});